/* Generate the engine bundle the edge function runs.
 *
 *   node build-edge.js
 *
 * The server must judge a submitted match with EXACTLY the same rules the game
 * used, so this bundles the real source files rather than keeping a second
 * copy. A hand-maintained duplicate would drift, and the day it drifts is the
 * day the leaderboard starts rejecting honest games.
 *
 * Re-run after changing anything in js/{geometry,engine,ai,grade,verify}.js
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SOURCES = ['geometry.js', 'engine.js', 'ai.js', 'grade.js', 'verify.js'];
const root = __dirname;

const body = SOURCES
  .map(f => '/* ===== js/' + f + ' ===== */\n' +
            fs.readFileSync(path.join(root, 'js', f), 'utf8'))
  .join('\n\n');

const out = `// GENERATED by build-edge.js — do not edit.
// Source of truth: js/{${SOURCES.map(f => f.replace('.js', '')).join(',')}}.js
//
// The sources are browser scripts that attach to window.KZ. A local \`window\`
// shim lets them load unchanged under Deno, so the server runs the identical
// rules the game does.
const window = {};

${body}

export const KZ = window.KZ;
`;

const dest = path.join(root, 'supabase/functions/submit/_engine.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, out);
console.log('supabase/functions/submit/_engine.js  ' + (out.length / 1024).toFixed(0) + ' KB  from ' + SOURCES.length + ' sources');
