// GENERATED by build-edge.js — do not edit.
// Source of truth: js/{geometry,engine,ai,grade,verify}.js
//
// The sources are browser scripts that attach to window.KZ. A local `window`
// shim lets them load unchanged under Deno, so the server runs the identical
// rules the game does.
const window = {};

/* ===== js/geometry.js ===== */
/* Kwanzaa Square — board geometry.
 *
 * Three concentric squares, 8 playable intersections each = 24 nodes.
 * The centre is sacred and never playable.
 *
 * Ring   0 = outer (Territory), 1 = middle (Strategy), 2 = inner (Mastery)
 * Pos    0=NW 1=N 2=NE 3=E 4=SE 5=S 6=SW 7=W   (clockwise from north-west)
 * Node id = ring * 8 + pos
 */
(function (KZ) {
  'use strict';

  var CENTER = 500;                 // viewBox is 0 0 1000 1000
  var HALF = [420, 280, 140];       // half-width of each ring
  var MIDPOINTS = [1, 3, 5, 7];     // N, E, S, W — the only nodes carrying spokes

  var nodes = [];
  for (var ring = 0; ring < 3; ring++) {
    var h = HALF[ring];
    var coords = [
      [CENTER - h, CENTER - h], // NW
      [CENTER,     CENTER - h], // N
      [CENTER + h, CENTER - h], // NE
      [CENTER + h, CENTER    ], // E
      [CENTER + h, CENTER + h], // SE
      [CENTER,     CENTER + h], // S
      [CENTER - h, CENTER + h], // SW
      [CENTER - h, CENTER    ]  // W
    ];
    for (var pos = 0; pos < 8; pos++) {
      nodes.push({
        id: ring * 8 + pos,
        ring: ring,
        pos: pos,
        x: coords[pos][0],
        y: coords[pos][1],
        corner: pos % 2 === 0
      });
    }
  }

  // --- adjacency ------------------------------------------------------------
  // Within a ring the eight nodes form a closed loop (corner-midpoint-corner).
  // Radial connectors ("spokes") join the rings at the four edge midpoints,
  // which is what lets a pawn travel between Territory, Strategy and Mastery.
  var adjacency = nodes.map(function () { return []; });

  function link(a, b) {
    if (adjacency[a].indexOf(b) === -1) adjacency[a].push(b);
    if (adjacency[b].indexOf(a) === -1) adjacency[b].push(a);
  }

  for (var r = 0; r < 3; r++) {
    for (var p = 0; p < 8; p++) link(r * 8 + p, r * 8 + ((p + 1) % 8));
  }
  MIDPOINTS.forEach(function (p) {
    link(0 * 8 + p, 1 * 8 + p);
    link(1 * 8 + p, 2 * 8 + p);
  });

  // --- trios (mills) --------------------------------------------------------
  // Only straight vertical or horizontal lines of three count. Diagonals never do.
  //   * 4 edges per ring x 3 rings = 12
  //   * 4 radial lines (one per midpoint direction) = 4
  var trios = [];
  for (var r2 = 0; r2 < 3; r2++) {
    var b = r2 * 8;
    trios.push([b + 0, b + 1, b + 2]); // top edge     — horizontal
    trios.push([b + 2, b + 3, b + 4]); // right edge   — vertical
    trios.push([b + 4, b + 5, b + 6]); // bottom edge  — horizontal
    trios.push([b + 6, b + 7, b + 0]); // left edge    — vertical
  }
  MIDPOINTS.forEach(function (p) {
    trios.push([p, 8 + p, 16 + p]);    // radial — vertical (N/S) or horizontal (E/W)
  });

  // trios that touch each node, precomputed for fast detection
  var triosByNode = nodes.map(function () { return []; });
  trios.forEach(function (t, i) {
    t.forEach(function (n) { triosByNode[n].push(i); });
  });

  // straight segments used to draw the board lines
  var segments = [];
  for (var r3 = 0; r3 < 3; r3++) {
    var bb = r3 * 8;
    segments.push([bb + 0, bb + 2], [bb + 2, bb + 4], [bb + 4, bb + 6], [bb + 6, bb + 0]);
  }
  MIDPOINTS.forEach(function (p) {
    segments.push([p, 16 + p]); // one straight run crossing all three rings
  });

  KZ.Geometry = {
    CENTER: CENTER,
    HALF: HALF,
    NODE_COUNT: 24,
    nodes: nodes,
    adjacency: adjacency,
    trios: trios,
    triosByNode: triosByNode,
    segments: segments,
    node: function (id) { return nodes[id]; },
    /** Is `orientation` of a trio vertical or horizontal (never diagonal). */
    trioOrientation: function (trio) {
      return nodes[trio[0]].x === nodes[trio[1]].x ? 'vertical' : 'horizontal';
    }
  };
})(typeof module !== 'undefined' && module.exports ? (module.exports.KZ = module.exports.KZ || {}) : (window.KZ = window.KZ || {}));


/* ===== js/engine.js ===== */
/* Kwanza Square — game engine.
 *
 * Pure state machine. No DOM, no rendering, no timers. Everything the UI and the
 * AI need to know about legality lives here so both agree on the rules.
 *
 * Rules (authoritative, per Martin):
 *   - 9 pawns per side, 24 intersections, sacred centre never playable.
 *   - Phase 1 placement: one pawn per intersection, a placement that would
 *     complete a trio is ILLEGAL — the player must choose another intersection.
 *     Nothing scores in Phase 1.
 *   - Phase 2 movement: vertical/horizontal to an ADJACENT FREE intersection.
 *     No diagonals, no skipping, no immediate back-and-forth. Every move can
 *     score, including the first (the old "first move cannot score" rule was
 *     dropped on Martin's instruction — it confused far more than it added).
 *   - A trio (3 in a straight line, never diagonal) grants the right to remove
 *     ANY one enemy pawn, including one standing inside a trio.
 *   - A round ends three ways: a side is reduced below three soldiers (it can
 *     never form a trio again), a side cannot move, or the draw limit is hit.
 */
(function (KZ) {
  'use strict';

  var G = KZ.Geometry;
  var PAWNS_PER_SIDE = 9;   // Martin's revised ruling: 9 leaves the board room to breathe
  var ROUNDS_TO_WIN = 2;
  var DRAW_LIMIT = 100; // moves without a capture -> round declared a draw
  // Martin's third ending: with only two soldiers left a side can never form a
  // trio again, so the round is already decided. Below three is a loss.
  var MIN_SOLDIERS = 3;

  function other(player) { return player === 'A' ? 'B' : 'A'; }

  function createMatch(opts) {
    opts = opts || {};
    var state = {
      mode: opts.mode || 'local',          // 'local' | 'ai'
      aiSide: opts.aiSide || 'B',
      difficulty: opts.difficulty || 'normal',
      names: opts.names || { A: 'Gold', B: 'Black' },
      pawnsPerSide: opts.pawns || PAWNS_PER_SIDE,
      // 2 = best of three (the standard match). 1 = a single-round Quick Match,
      // for someone who has a few minutes rather than a quarter of an hour.
      roundsToWin: opts.roundsToWin || ROUNDS_TO_WIN,
      round: 1,
      scores: { A: 0, B: 0 },
      roundHistory: [],
      matchOver: false,
      matchWinner: null,
      startingPlayer: 'A',
      // Every action of the whole match, in order, as compact keys. This is
      // what a server replays to re-prove a submitted result: the client is
      // never believed. 'R' marks the start of a new round.
      actionLog: []
    };
    resetRound(state);
    return state;
  }

  function resetRound(state) {
    if (!state.actionLog) state.actionLog = [];
    state.phase = 'placement';
    state.board = new Array(G.NODE_COUNT).fill(null);
    state.turn = state.startingPlayer;
    var n = state.pawnsPerSide || PAWNS_PER_SIDE;
    state.toPlace = { A: n, B: n };
    state.onBoard = { A: 0, B: 0 };
    state.awaitingCapture = null;
    state.lastMove = { A: null, B: null };
    state.movesMade = { A: 0, B: 0 };
    state.movesSinceCapture = 0;
    state.activeTrios = [];   // every trio standing on the board
    state.scoredTrios = [];   // only the trio(s) formed by the move just played
    state.roundOver = false;
    state.roundWinner = null;
    state.roundReason = '';
    state.log = [];
  }

  function clone(state) {
    return {
      mode: state.mode, aiSide: state.aiSide, difficulty: state.difficulty,
      names: state.names, pawnsPerSide: state.pawnsPerSide,
      roundsToWin: state.roundsToWin, round: state.round,
      scores: { A: state.scores.A, B: state.scores.B },
      roundHistory: state.roundHistory.slice(),
      matchOver: state.matchOver, matchWinner: state.matchWinner,
      startingPlayer: state.startingPlayer,
      actionLog: state.actionLog.slice(),
      phase: state.phase,
      board: state.board.slice(),
      turn: state.turn,
      toPlace: { A: state.toPlace.A, B: state.toPlace.B },
      onBoard: { A: state.onBoard.A, B: state.onBoard.B },
      awaitingCapture: state.awaitingCapture,
      lastMove: {
        A: state.lastMove.A ? { from: state.lastMove.A.from, to: state.lastMove.A.to } : null,
        B: state.lastMove.B ? { from: state.lastMove.B.from, to: state.lastMove.B.to } : null
      },
      movesMade: { A: state.movesMade.A, B: state.movesMade.B },
      movesSinceCapture: state.movesSinceCapture,
      activeTrios: state.activeTrios.slice(),
      scoredTrios: state.scoredTrios.slice(),
      roundOver: state.roundOver, roundWinner: state.roundWinner,
      roundReason: state.roundReason,
      log: state.log.slice()
    };
  }

  // --- trio detection -------------------------------------------------------

  /** Indices of trios that are completely owned by `player` and contain `node`. */
  function triosAt(board, node, player) {
    var found = [];
    var candidates = G.triosByNode[node];
    for (var i = 0; i < candidates.length; i++) {
      var t = G.trios[candidates[i]];
      if (board[t[0]] === player && board[t[1]] === player && board[t[2]] === player) {
        found.push(candidates[i]);
      }
    }
    return found;
  }

  /** Every trio currently held by `player` — used for the board glow. */
  function allTrios(board, player) {
    var found = [];
    for (var i = 0; i < G.trios.length; i++) {
      var t = G.trios[i];
      if (board[t[0]] === player && board[t[1]] === player && board[t[2]] === player) found.push(i);
    }
    return found;
  }

  /** Would dropping a pawn on `node` complete a trio? Placement forbids this. */
  function placementFormsTrio(board, node, player) {
    board[node] = player;
    var hit = triosAt(board, node, player).length > 0;
    board[node] = null;
    return hit;
  }

  // --- legality -------------------------------------------------------------

  function legalPlacements(state) {
    var player = state.turn;
    var free = [];
    var i;
    for (i = 0; i < G.NODE_COUNT; i++) if (state.board[i] === null) free.push(i);

    var legal = free.filter(function (n) {
      return !placementFormsTrio(state.board, n, player);
    });

    // Defensive only: if every remaining intersection would force a trio there is
    // no legal choice left, so the trio is allowed but still scores nothing.
    return legal.length ? legal : free;
  }

  function isBacktrack(state, player, from, to) {
    var last = state.lastMove[player];
    return !!last && last.from === to && last.to === from;
  }

  function legalMovesFrom(state, from) {
    var player = state.turn;
    if (state.board[from] !== player) return [];
    var out = [];
    var adj = G.adjacency[from];
    for (var i = 0; i < adj.length; i++) {
      var to = adj[i];
      if (state.board[to] !== null) continue;          // no moving into an occupied space
      if (isBacktrack(state, player, from, to)) continue; // no back-and-forth
      out.push(to);
    }
    return out;
  }

  function allMoves(state, player) {
    var moves = [];
    for (var from = 0; from < G.NODE_COUNT; from++) {
      if (state.board[from] !== player) continue;
      var adj = G.adjacency[from];
      for (var i = 0; i < adj.length; i++) {
        var to = adj[i];
        if (state.board[to] !== null) continue;
        if (isBacktrack(state, player, from, to)) continue;
        moves.push({ from: from, to: to });
      }
    }
    return moves;
  }

  /** Any enemy pawn may be taken — including one standing inside a trio. */
  function capturableNodes(state, player) {
    var foe = other(player);
    var out = [];
    for (var i = 0; i < G.NODE_COUNT; i++) if (state.board[i] === foe) out.push(i);
    return out;
  }

  /** Every action the side to move may legally take right now. */
  function legalActions(state) {
    if (state.roundOver || state.matchOver) return [];
    if (state.awaitingCapture) {
      return capturableNodes(state, state.awaitingCapture).map(function (n) {
        return { type: 'capture', node: n };
      });
    }
    if (state.phase === 'placement') {
      return legalPlacements(state).map(function (n) { return { type: 'place', node: n }; });
    }
    return allMoves(state, state.turn).map(function (m) {
      return { type: 'move', from: m.from, to: m.to };
    });
  }

  // --- applying actions -----------------------------------------------------

  function log(state, text) {
    state.log.push({ round: state.round, text: text });
    if (state.log.length > 200) state.log.shift();
  }

  function label(state, player) {
    return state.names[player] || player;
  }

  /**
   * Apply an action. Mutates `state`. Returns a list of UI events describing
   * what visibly happened, e.g. [{type:'trio', trios:[...]}, {type:'capture'}].
   */
  function apply(state, action) {
    var events = [];
    if (state.roundOver || state.matchOver) return events;
    var player = state.awaitingCapture || state.turn;

    // A trio only "scores" at the moment it is formed. It then stays standing on
    // the board, and a standing trio must not keep signalling a capture is due —
    // that is what made an old trio look like a fresh one.
    if (action.type !== 'capture') state.scoredTrios = [];

    if (action.type === 'place') {
      if (state.phase !== 'placement' || state.awaitingCapture) return events;
      if (state.board[action.node] !== null) return events;
      state.actionLog.push('p' + action.node);
      state.board[action.node] = player;
      state.toPlace[player]--;
      state.onBoard[player]++;
      log(state, label(state, player) + ' places a soldier.');
      events.push({ type: 'place', node: action.node, player: player });

      if (state.toPlace.A === 0 && state.toPlace.B === 0) {
        state.phase = 'movement';
        log(state, 'All ' + (state.pawnsPerSide * 2) + ' soldiers placed — the movement phase begins.');
        events.push({ type: 'phase', phase: 'movement' });
      }
      endTurn(state, events);
      return events;
    }

    if (action.type === 'move') {
      if (state.phase !== 'movement' || state.awaitingCapture) return events;
      if (state.board[action.from] !== player) return events;
      if (legalMovesFrom(state, action.from).indexOf(action.to) === -1) return events;

      state.actionLog.push('m' + action.from + '>' + action.to);
      state.board[action.from] = null;
      state.board[action.to] = player;
      state.lastMove[player] = { from: action.from, to: action.to };
      state.movesSinceCapture++;
      events.push({ type: 'move', from: action.from, to: action.to, player: player });

      state.movesMade[player]++;

      var formed = triosAt(state.board, action.to, player);
      if (formed.length) {
        state.awaitingCapture = player;
        state.scoredTrios = formed.map(function (i) { return { trio: i, player: player }; });
        log(state, label(state, player) + ' scores a trio — remove an enemy soldier.');
        events.push({ type: 'trio', trios: formed, player: player });
        refreshTrios(state);
        return events; // same player continues, to take a pawn
      }
      refreshTrios(state);
      endTurn(state, events);
      return events;
    }

    if (action.type === 'capture') {
      if (!state.awaitingCapture) return events;
      var taker = state.awaitingCapture;
      if (state.board[action.node] !== other(taker)) return events;
      state.actionLog.push('x' + action.node);
      state.board[action.node] = null;
      state.onBoard[other(taker)]--;
      state.awaitingCapture = null;
      state.movesSinceCapture = 0;
      log(state, label(state, taker) + ' captures a soldier of ' + label(state, other(taker)) + '.');
      events.push({ type: 'capture', node: action.node, player: taker, victim: other(taker) });
      refreshTrios(state);
      endTurn(state, events);
      return events;
    }

    return events;
  }

  function refreshTrios(state) {
    state.activeTrios = allTrios(state.board, 'A')
      .map(function (i) { return { trio: i, player: 'A' }; })
      .concat(allTrios(state.board, 'B').map(function (i) { return { trio: i, player: 'B' }; }));
  }

  function endTurn(state, events) {
    state.turn = other(state.turn);
    checkRoundEnd(state, events);
  }

  function checkRoundEnd(state, events) {
    if (state.roundOver) return;
    var mover = state.turn;
    var foe = other(mover);

    // A side reduced below three soldiers has lost: three is the fewest that can
    // ever form a trio again.
    if (state.phase === 'movement' && state.onBoard[mover] < MIN_SOLDIERS) {
      return finishRound(state, foe, shortHanded(state, mover), events);
    }
    if (state.phase === 'movement' && state.onBoard[foe] < MIN_SOLDIERS) {
      return finishRound(state, mover, shortHanded(state, foe), events);
    }
    // A side that cannot move loses the round.
    if (state.phase === 'movement' && allMoves(state, mover).length === 0) {
      return finishRound(state, foe, label(state, mover) + ' cannot move.', events);
    }
    if (state.phase === 'movement' && state.movesSinceCapture >= DRAW_LIMIT) {
      return finishRound(state, null, 'No capture in ' + DRAW_LIMIT + ' moves — the round is drawn.', events);
    }
  }

  function shortHanded(state, side) {
    var n = state.onBoard[side];
    if (n === 0) return label(state, side) + ' has no soldiers left.';
    return label(state, side) + ' is down to ' + (n === 1 ? 'one soldier' : 'two soldiers') +
      ' and can never form a trio again.';
  }

  function finishRound(state, winner, reason, events) {
    state.roundOver = true;
    state.roundWinner = winner;
    state.roundReason = reason;
    if (winner) state.scores[winner]++;
    state.roundHistory.push({ round: state.round, winner: winner, reason: reason });
    log(state, 'Round ' + state.round + ': ' + (winner ? label(state, winner) + ' wins. ' : 'Drawn. ') + reason);
    events.push({ type: 'round-over', winner: winner, reason: reason });

    if (winner && state.scores[winner] >= (state.roundsToWin || ROUNDS_TO_WIN)) {
      state.matchOver = true;
      state.matchWinner = winner;
      log(state, label(state, winner) + ' takes the match ' + state.scores[winner] + '–' + state.scores[other(winner)] + '.');
      events.push({ type: 'match-over', winner: winner });
    }
  }

  /** Begin the next round. The loser of the toss alternates who opens. */
  function nextRound(state) {
    if (state.matchOver) return state;
    state.round++;
    state.startingPlayer = other(state.startingPlayer);
    var log = state.actionLog;
    resetRound(state);
    state.actionLog = log;
    state.actionLog.push('R');
    return state;
  }

  KZ.Engine = {
    PAWNS_PER_SIDE: PAWNS_PER_SIDE,
    ROUNDS_TO_WIN: ROUNDS_TO_WIN,
    DRAW_LIMIT: DRAW_LIMIT,
    MIN_SOLDIERS: MIN_SOLDIERS,
    other: other,
    createMatch: createMatch,
    resetRound: resetRound,
    nextRound: nextRound,
    clone: clone,
    triosAt: triosAt,
    allTrios: allTrios,
    placementFormsTrio: placementFormsTrio,
    legalPlacements: legalPlacements,
    legalMovesFrom: legalMovesFrom,
    allMoves: allMoves,
    capturableNodes: capturableNodes,
    legalActions: legalActions,
    apply: apply,
    refreshTrios: refreshTrios
  };
})(typeof module !== 'undefined' && module.exports ? (module.exports.KZ = module.exports.KZ || {}) : (window.KZ = window.KZ || {}));


/* ===== js/ai.js ===== */
/* Kwanza Square — the Kwanza AI.
 *
 * The three levels differ in TEMPERAMENT, not just search depth. That matters
 * because of how this board behaves: with 20 soldiers on 24 points, the fastest
 * win is not to capture anything, it is to take away the opponent's last free
 * step and win on "cannot move". A strong engine finds that immediately and the
 * game is over before it starts.
 *
 * So `squeeze` scales how much the AI values strangling your mobility:
 *
 *   Beginner — squeeze 0. Never plays to suffocate you. Chases its own trios,
 *              blocks yours only half-heartedly, and plays with a wide random
 *              spread so it makes ordinary human mistakes. One ply.
 *   Skilled  — squeeze 0.35. Will take a good blocking move when it sees one,
 *              but does not hunt for the strangle. Two ply, mild randomness.
 *   Master   — squeeze 1. Full strength, plays the suffocation line on purpose,
 *              no randomness. Four ply in movement. This one is hard to beat.
 */
(function (KZ) {
  'use strict';

  var G = KZ.Geometry;
  var E = KZ.Engine;

  var LEVELS = {
    easy:   { label: 'Beginner', place: 1, move: 1, noise: 34, squeeze: 0,    block: 0.55, build: 1 },
    normal: { label: 'Skilled',  place: 2, move: 2, noise: 11, squeeze: 0.35, block: 0.85, build: 1 },
    hard:   { label: 'Master',   place: 3, move: 4, noise: 0,  squeeze: 1,    block: 1.15, build: 1 }
  };

  // Midpoints carry the radial connectors, so they are worth more than corners.
  var DEGREE = G.adjacency.map(function (a) { return a.length; });

  function trioCounts(board, trio) {
    var a = 0, b = 0, empty = 0;
    for (var i = 0; i < 3; i++) {
      var v = board[trio[i]];
      if (v === 'A') a++; else if (v === 'B') b++; else empty++;
    }
    return { A: a, B: b, empty: empty };
  }

  function mobility(state, player) {
    var n = 0;
    for (var from = 0; from < G.NODE_COUNT; from++) {
      if (state.board[from] !== player) continue;
      var adj = G.adjacency[from];
      for (var i = 0; i < adj.length; i++) if (state.board[adj[i]] === null) n++;
    }
    return n;
  }

  function evaluate(state, me, cfg) {
    var foe = E.other(me);

    if (state.roundOver) {
      if (state.roundWinner === me) return 100000;
      if (state.roundWinner === foe) return -100000;
      return 0;
    }

    var score = 0;

    // Material — every capture is a step towards emptying the enemy side.
    score += (state.onBoard[me] - state.onBoard[foe]) * 120;

    // Trios held, and trios one step away. `build` drives its own attack,
    // `block` drives how urgently it answers yours.
    for (var i = 0; i < G.trios.length; i++) {
      var c = trioCounts(state.board, G.trios[i]);
      var mine = c[me], theirs = c[foe];
      if (mine === 3) score += 45 * cfg.build;
      else if (mine === 2 && c.empty === 1) score += 14 * cfg.build;
      else if (mine === 1 && c.empty === 2) score += 3 * cfg.build;
      if (theirs === 3) score -= 45 * cfg.block;
      else if (theirs === 2 && c.empty === 1) score -= 17 * cfg.block;
      else if (theirs === 1 && c.empty === 2) score -= 3 * cfg.block;
    }

    // Mobility and the strangle. All of it scales with `squeeze`, except the
    // AI's own survival — it always avoids trapping itself.
    var myMob = mobility(state, me), foeMob = mobility(state, foe);
    score += (myMob - foeMob) * 6 * cfg.squeeze;
    if (state.phase === 'movement') {
      if (myMob === 0) score -= 5000;                     // never self-trap
      if (myMob <= 2) score -= (3 - myMob) * 40;
      if (foeMob === 0) score += 5000 * cfg.squeeze;      // only hunt the kill if allowed
      if (foeMob <= 2) score += (3 - foeMob) * 40 * cfg.squeeze;
    }

    // Hold the connectors — the only way between the three rings.
    for (var n = 0; n < G.NODE_COUNT; n++) {
      if (state.board[n] === me) score += DEGREE[n] * 2;
      else if (state.board[n] === foe) score -= DEGREE[n] * 2;
    }

    return score;
  }

  function search(state, depth, alpha, beta, me, cfg, budget) {
    if (budget.nodes++ > budget.limit) return evaluate(state, me, cfg);
    if (depth <= 0 || state.roundOver || state.matchOver) return evaluate(state, me, cfg);

    var actions = E.legalActions(state);
    if (!actions.length) return evaluate(state, me, cfg);

    var mover = state.awaitingCapture || state.turn;
    var maximizing = mover === me;
    var best = maximizing ? -Infinity : Infinity;

    for (var i = 0; i < actions.length; i++) {
      var next = E.clone(state);
      E.apply(next, actions[i]);
      var value = search(next, depth - 1, alpha, beta, me, cfg, budget);
      if (maximizing) {
        if (value > best) best = value;
        if (best > alpha) alpha = best;
      } else {
        if (value < best) best = value;
        if (best < beta) beta = best;
      }
      if (beta <= alpha) break; // prune
    }
    return best;
  }

  /** Choose an action for the side to move (or to capture). */
  function chooseAction(state) {
    var mover = state.awaitingCapture || state.turn;
    var actions = E.legalActions(state);
    if (!actions.length) return null;
    if (actions.length === 1) return actions[0];

    var cfg = LEVELS[state.difficulty] || LEVELS.normal;
    var depth = state.phase === 'placement' ? cfg.place : cfg.move;
    var budget = { nodes: 0, limit: 60000 };

    var scored = actions.map(function (action) {
      var next = E.clone(state);
      E.apply(next, action);
      var value = search(next, depth - 1, -Infinity, Infinity, mover, cfg, budget);
      if (cfg.noise) value += (Math.random() * 2 - 1) * cfg.noise;
      return { action: action, value: value };
    });

    scored.sort(function (x, y) { return y.value - x.value; });
    return scored[0].action;
  }

  /**
   * Score every legal action from the mover's point of view, strongest first.
   * Deterministic — no randomness — because this is what the grader judges a
   * human move against, and a grade must never change between two identical games.
   */
  function scoreActions(state, depth) {
    var mover = state.awaitingCapture || state.turn;
    var actions = E.legalActions(state);
    if (!actions.length) return [];
    var cfg = LEVELS.hard;
    var budget = { nodes: 0, limit: 40000 };
    var d = depth || 2;

    return actions.map(function (action) {
      var next = E.clone(state);
      E.apply(next, action);
      return { action: action, value: search(next, d - 1, -Infinity, Infinity, mover, cfg, budget) };
    }).sort(function (x, y) { return y.value - x.value; });
  }

  KZ.AI = {
    LEVELS: LEVELS,
    chooseAction: chooseAction,
    scoreActions: scoreActions,
    evaluate: evaluate
  };
})(typeof module !== 'undefined' && module.exports ? (module.exports.KZ = module.exports.KZ || {}) : (window.KZ = window.KZ || {}));


/* ===== js/grade.js ===== */
/* Kwanza Square — grading a player's thinking.
 *
 * The point, in Martin's words: most people will lose to the AI, so losing
 * badly and losing well must not look the same. This measures whether the moves
 * showed strategy or were close to random, and it works just as well in a
 * defeat as in a win.
 *
 * Method, per decision:
 *   1. Score every move the player COULD have made (deterministically).
 *   2. See where the move they actually chose ranked between the best and the
 *      worst available.
 *   3. quality = (played - worst) / (best - worst)  ->  0 for the worst move
 *      available, 1 for the best.
 *
 * Decisions where every option is equal, or where only one move is legal, carry
 * no information about skill and are excluded rather than counted as perfect.
 *
 * Accuracy is the mean quality across graded decisions. It is a judgement
 * against this engine's opinion, not against absolute truth — a strong human
 * may play a good move the engine dislikes.
 *
 * Every decision is also recorded as a move list, so a future server could
 * replay a game and confirm both the result and the grade independently.
 */
(function (KZ) {
  'use strict';

  var AI = KZ.AI;

  var GRADE_DEPTH = 2;      // deep enough to be meaningful, fast enough on a phone
  var FLAT_SPREAD = 10;     // below this, the options are effectively equivalent
  var BLUNDER_SPREAD = 60;  // a decision that genuinely mattered
  var BLUNDER_QUALITY = 0.25;

  var BANDS = [
    { min: 92, grade: 'A+', note: 'Masterful. Nearly every move was the strongest available.' },
    { min: 85, grade: 'A',  note: 'Excellent judgement. You saw the board clearly.' },
    { min: 76, grade: 'B',  note: 'Strong play with a few missed chances.' },
    { min: 66, grade: 'C',  note: 'Sound instincts, but several moves gave ground away.' },
    { min: 55, grade: 'D',  note: 'The shape of a plan is there. Watch your opponent\'s trios.' },
    { min: 0,  grade: 'E',  note: 'Mostly reacting rather than planning. Try the tutorial.' }
  ];

  function newCard() {
    return {
      decisions: 0,      // graded decisions
      skipped: 0,        // forced or equivalent-option decisions
      sum: 0,            // summed quality
      best: 0,           // times the strongest move was chosen
      blunders: 0,
      trios: 0,
      captures: 0,
      lost: 0,           // own soldiers taken
      moves: []          // the move list, for later verification
    };
  }

  /**
   * Judge one decision before it is played.
   * `state` must be the position BEFORE the action.
   */
  function assess(state, action) {
    var scored = AI.scoreActions(state, GRADE_DEPTH);
    if (scored.length < 2) return { forced: true };

    var best = scored[0].value;
    var worst = scored[scored.length - 1].value;
    var spread = best - worst;
    if (spread < FLAT_SPREAD) return { forced: true };

    var key = actionKey(action);
    var played = null;
    for (var i = 0; i < scored.length; i++) {
      if (actionKey(scored[i].action) === key) { played = scored[i].value; break; }
    }
    if (played === null) return { forced: true }; // not a legal action; nothing to judge

    var quality = (played - worst) / spread;
    return {
      forced: false,
      quality: quality,
      wasBest: played >= best - 1e-9,
      blunder: quality < BLUNDER_QUALITY && spread >= BLUNDER_SPREAD,
      spread: spread
    };
  }

  function actionKey(a) {
    return a.type === 'move' ? 'm' + a.from + '>' + a.to
      : a.type === 'place' ? 'p' + a.node
      : 'x' + a.node;
  }

  /** Fold one judged decision into a card. */
  function record(card, action, verdict) {
    card.moves.push(actionKey(action));
    if (!verdict || verdict.forced) { card.skipped++; return; }
    card.decisions++;
    card.sum += verdict.quality;
    if (verdict.wasBest) card.best++;
    if (verdict.blunder) card.blunders++;
  }

  /** Final numbers for a card. */
  function summarise(card) {
    var accuracy = card.decisions ? (card.sum / card.decisions) * 100 : null;
    var band = null;
    if (accuracy !== null) {
      for (var i = 0; i < BANDS.length; i++) {
        if (accuracy >= BANDS[i].min) { band = BANDS[i]; break; }
      }
    }
    return {
      accuracy: accuracy,
      accuracyText: accuracy === null ? '—' : Math.round(accuracy) + '%',
      grade: band ? band.grade : '—',
      note: band ? band.note : 'Not enough real decisions to grade this round.',
      bestRate: card.decisions ? Math.round((card.best / card.decisions) * 100) : 0,
      decisions: card.decisions,
      blunders: card.blunders,
      trios: card.trios,
      captures: card.captures,
      lost: card.lost,
      moves: card.moves
    };
  }

  // --------------------------------------------------------------- persistence

  var STORE = 'kwanza-record';

  function loadRecord() {
    try {
      var raw = localStorage.getItem(STORE);
      if (raw) return JSON.parse(raw);
    } catch (e) {}
    return { played: 0, won: 0, lost: 0, drawn: 0, bestAccuracy: null, sumAccuracy: 0, graded: 0, streak: 0, bestStreak: 0 };
  }

  function saveRecord(rec) {
    try { localStorage.setItem(STORE, JSON.stringify(rec)); } catch (e) {}
  }

  /** Fold a finished match into the player's lifetime record. */
  function commitMatch(result) {
    var rec = loadRecord();
    rec.played++;
    if (result.won) { rec.won++; rec.streak++; if (rec.streak > rec.bestStreak) rec.bestStreak = rec.streak; }
    else if (result.drawn) { rec.drawn++; }
    else { rec.lost++; rec.streak = 0; }

    if (typeof result.accuracy === 'number') {
      rec.sumAccuracy += result.accuracy;
      rec.graded++;
      if (rec.bestAccuracy === null || result.accuracy > rec.bestAccuracy) rec.bestAccuracy = result.accuracy;
    }
    saveRecord(rec);
    return rec;
  }

  function averageAccuracy(rec) {
    return rec.graded ? rec.sumAccuracy / rec.graded : null;
  }

  KZ.Grade = {
    GRADE_DEPTH: GRADE_DEPTH,
    BANDS: BANDS,
    newCard: newCard,
    assess: assess,
    record: record,
    summarise: summarise,
    actionKey: actionKey,
    loadRecord: loadRecord,
    saveRecord: saveRecord,
    commitMatch: commitMatch,
    averageAccuracy: averageAccuracy
  };
})(typeof module !== 'undefined' && module.exports ? (module.exports.KZ = module.exports.KZ || {}) : (window.KZ = window.KZ || {}));


/* ===== js/verify.js ===== */
/* Kwanza Square — re-proving a submitted match.
 *
 * The client is never believed. A submitted game is a list of every action in
 * order; this replays it against the same engine, rejects anything illegal, and
 * works out the result and the grade for itself. Whatever the app claimed is
 * only ever compared against what the replay produced.
 *
 * Runs unchanged in Node (tests) and in Deno (the edge function).
 */
(function (KZ) {
  'use strict';

  var E = KZ.Engine, Gr = KZ.Grade;

  var MAX_ACTIONS = 20000;   // a real match is a few hundred; this is a DoS guard

  var OUTCOME = { win: 1.0, draw: 0.5, loss: 0.2 };

  /** Points for one match: how it ended, weighted by how well it was played. */
  function pointsFor(result, accuracy) {
    var acc = typeof accuracy === 'number' ? accuracy : 0;
    return OUTCOME[result] * (0.5 + acc / 100);
  }

  function parseKey(key) {
    if (key === 'R') return { type: 'next-round' };
    if (key[0] === 'p') return { type: 'place', node: +key.slice(1) };
    if (key[0] === 'x') return { type: 'capture', node: +key.slice(1) };
    if (key[0] === 'm') {
      var bits = key.slice(1).split('>');
      return { type: 'move', from: +bits[0], to: +bits[1] };
    }
    return null;
  }

  function sameAction(a, b) {
    if (a.type !== b.type) return false;
    if (a.type === 'move') return a.from === b.from && a.to === b.to;
    return a.node === b.node;
  }

  /**
   * @param submission {level, pawns, roundsToWin, humanSide, actionLog[]}
   * @returns {ok, reason, result, accuracy, decisions, points, rounds}
   */
  function replay(submission) {
    var s = submission || {};
    var log = s.actionLog;

    if (!Array.isArray(log)) return fail('no action log');
    if (!log.length) return fail('empty action log');
    if (log.length > MAX_ACTIONS) return fail('action log too long');
    if (['easy', 'normal', 'hard'].indexOf(s.level) === -1) return fail('unknown level');
    if (['A', 'B'].indexOf(s.humanSide) === -1) return fail('unknown side');
    if (!(s.pawns >= 5 && s.pawns <= 12)) return fail('pawn count out of range');
    if (!(s.roundsToWin >= 1 && s.roundsToWin <= 3)) return fail('round count out of range');

    var state = E.createMatch({
      mode: 'ai', aiSide: s.humanSide === 'A' ? 'B' : 'A',
      difficulty: s.level, pawns: s.pawns, roundsToWin: s.roundsToWin
    });
    var card = Gr.newCard();

    for (var i = 0; i < log.length; i++) {
      var action = parseKey(log[i]);
      if (!action) return fail('unreadable action at ' + i);

      if (action.type === 'next-round') {
        if (!state.roundOver) return fail('round advanced before it ended, at ' + i);
        if (state.matchOver) return fail('round advanced after the match ended, at ' + i);
        E.nextRound(state);
        continue;
      }

      if (state.roundOver || state.matchOver) return fail('action played after the round ended, at ' + i);

      // The action must be one the engine would have allowed at this moment.
      var legal = E.legalActions(state);
      var allowed = false;
      for (var j = 0; j < legal.length; j++) {
        if (sameAction(legal[j], action)) { allowed = true; break; }
      }
      if (!allowed) return fail('illegal action at ' + i + ': ' + log[i]);

      // Grade only the human's own decisions, exactly as the app does.
      var mover = state.awaitingCapture || state.turn;
      if (mover === s.humanSide) Gr.record(card, action, Gr.assess(state, action));

      E.apply(state, action);
    }

    if (!state.matchOver) return fail('the match never finished');

    var result = state.matchWinner === s.humanSide ? 'win'
      : (!state.matchWinner ? 'draw' : 'loss');
    var summary = Gr.summarise(card);
    // Round the accuracy FIRST, then derive points from that same rounded
    // figure. Otherwise the stored points and the stored accuracy do not
    // reconcile, and a leaderboard people can audit has to add up.
    var accuracy = Math.round((summary.accuracy === null ? 0 : summary.accuracy) * 100) / 100;

    return {
      ok: true,
      reason: null,
      result: result,
      accuracy: accuracy,
      decisions: summary.decisions,
      points: Math.round(pointsFor(result, accuracy) * 1000) / 1000,
      rounds: state.round,
      scores: { A: state.scores.A, B: state.scores.B }
    };
  }

  function fail(reason) {
    return { ok: false, reason: reason, result: null, accuracy: 0, decisions: 0, points: 0 };
  }

  KZ.Verify = { replay: replay, pointsFor: pointsFor, MAX_ACTIONS: MAX_ACTIONS };
})(typeof module !== 'undefined' && module.exports ? (module.exports.KZ = module.exports.KZ || {}) : (window.KZ = window.KZ || {}));


export const KZ = window.KZ;
